[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
rust-version = "1.88"
publish = false

[workspace.dependencies]
base64 = "0.23"
dirs = "7"
keyring-core = "1"
rpassword = "7"
ureq = { version = "3", features = ["json"] }
clap = { version = "4", features = ["derive"] }
comrak = { version = "0.55", default-features = false }
emojis = "0.9"
globset = "0.4"
ignore = "0.4"
percent-encoding = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_norway = "0.9"

rfluence-convert = { path = "crates/rfluence-convert" }
rfluence-client = { path = "crates/rfluence-client" }

insta = "1"
mockito = "1"
similar-asserts = "1"
